Test hack
JelfsMaterialsGroup/stko pull request #58
Opened 2020-12-18 17:05 UTC by 08haganh

Pull request

2020-12-19 09:57 UTC, stevenbennett96 approved these changes

2021-01-03 14:40 UTC, andrewtarzia requested changes

2021-01-03 14:40 UTC, andrewtarzia commented on tests/optimizers/test_rdkit.py
> +from stko.optimizers import MMFF, UFF, ETKDG
why have you imported these, but used `stko.MMFF()` below? (for example). Make sure your imports are cleaned up.

2021-01-03 14:40 UTC, andrewtarzia commented on tests/optimizers/test_rdkit.py
> +import rdkit.Chem as Chem
Unused. a Linter in your code editor will check unused import statements.

2021-05-25 09:41 UTC, andrewtarzia commented
Closing because it is outdated.

2021-05-25 09:41 UTC, closed without merging